[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/book-a-call"
  to = "https://calendly.com/puja-2fa/initialmeeting"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
