export const siteConfig = {
    name: "BuyersMatch",
    logoText: "BM",
    contact: {
        address: "Glen Waverley, VIC 3150",
        phones: ["+61 466 914 929"],
        email: "info@buyersmatch.com.au",
        calendly: "https://calendly.com/buyersmatch",
    },
    socials: [
        { name: "facebook", icon: "Facebook", url: "https://www.facebook.com/buyersmatchaustralia" },
        { name: "instagram", icon: "Instagram", url: "https://www.instagram.com/buyers_match/?hl=en" },
        { name: "youtube", icon: "YouTube", url: "https://www.youtube.com/@BuyersMatch" },
        { name: "linkedin", icon: "LinkedIn", url: "https://www.linkedin.com/in/puja-dhanetwal/?originalSubdomain=au" },
        { name: "tiktok", icon: "TikTok", url: "#" },
        { name: "maps", icon: "Maps", url: "https://www.google.com/maps/place/BuyersMatch/@-36.5712557,99.6994519,3z/data=!4m6!3m5!1s0x9a64e54f2968b55:0x765d586cc54a73c!8m2!3d-24.1501978!4d136.0132792!16s%2Fg%2F11v6z05n76?entry=ttu&g_ep=EgoyMDI2MDIwOC4wIKXMDSoASAFQAw%3D%3D" },
    ],
    navigation: [
        { id: "help", label: "Who We Help" },
        { id: "approach", label: "How We Help" },
        { id: "process", label: "Our Process" },
        { id: "why-choose", label: "Why Us" },
        { id: "case-studies", label: "Results" },
        { id: "testimonials", label: "Reviews" },
        { id: "faq", label: "FAQ" },
    ],
    videoTestimonials: [
        { id: 1, name: "Client Success", quote: "Found the perfect property with expert guidance", youtubeId: "vmZ-wy00s-k", image: "https://img.youtube.com/vi/vmZ-wy00s-k/maxresdefault.jpg" },
        { id: 2, name: "Client Success", quote: "Strategic negotiation saved us thousands", youtubeId: "X3TZe_DaO5g", image: "https://img.youtube.com/vi/X3TZe_DaO5g/maxresdefault.jpg" },
        { id: 3, name: "Client Success", quote: "Professional support through the entire journey", youtubeId: "30we2JzIsE8", image: "https://img.youtube.com/vi/30we2JzIsE8/maxresdefault.jpg" },
        { id: 4, name: "Client Success", quote: "Expert market knowledge and insights", youtubeId: "q3IfD-X7Cf0", image: "https://img.youtube.com/vi/q3IfD-X7Cf0/maxresdefault.jpg" },
        { id: 5, name: "Client Success", quote: "Transparent and honest communication", youtubeId: "tbkddtd7I_8", image: "https://img.youtube.com/vi/tbkddtd7I_8/maxresdefault.jpg" },
        { id: 6, name: "Client Success", quote: "Highly recommended for property buyers", youtubeId: "caH8lakaud0", image: "https://img.youtube.com/vi/caH8lakaud0/maxresdefault.jpg" },
        { id: 7, name: "Client Success", quote: "Exceptional service and dedication", youtubeId: "LSIsyzuSobY", image: "https://img.youtube.com/vi/LSIsyzuSobY/maxresdefault.jpg" },
        { id: 8, name: "Client Success", quote: "Making property buying stress-free", youtubeId: "5UrWOfea4zA", image: "https://img.youtube.com/vi/5UrWOfea4zA/maxresdefault.jpg" },
        { id: 9, name: "Client Success", quote: "The best decision for our home search", youtubeId: "-KYMMLq-miQ", image: "https://img.youtube.com/vi/-KYMMLq-miQ/maxresdefault.jpg" },
        { id: 10, name: "Client Success", quote: "Top-tier negotiation and strategy", youtubeId: "CKQOAuvINdI", image: "https://img.youtube.com/vi/CKQOAuvINdI/maxresdefault.jpg" },
        { id: 11, name: "Client Success", quote: "Invaluable help in a competitive market", youtubeId: "-9kClkczOeg", image: "https://img.youtube.com/vi/-9kClkczOeg/maxresdefault.jpg" },
        { id: 12, name: "Client Success", quote: "A seamless property buying experience", youtubeId: "E6Dp_iM07lg", image: "https://img.youtube.com/vi/E6Dp_iM07lg/maxresdefault.jpg" },
        { id: 13, name: "Client Success", quote: "Patient and thorough property search", youtubeId: "ISsxVHcajes", image: "https://img.youtube.com/vi/ISsxVHcajes/maxresdefault.jpg" },
        { id: 14, name: "Client Success", quote: "Personalized approach to our needs", youtubeId: "d9HTedtaH74", image: "https://img.youtube.com/vi/d9HTedtaH74/maxresdefault.jpg" },
        { id: 15, name: "Client Success", quote: "Reliable and expert property advice", youtubeId: "u2KrdsZymoM", image: "https://img.youtube.com/vi/u2KrdsZymoM/maxresdefault.jpg" },
        { id: 16, name: "Client Success", quote: "Found our dream home faster than expected", youtubeId: "EZ6xhMKm7DM", image: "https://img.youtube.com/vi/EZ6xhMKm7DM/maxresdefault.jpg" },
        { id: 17, name: "Client Success", quote: "Skilled support for property investment", youtubeId: "oT-lSZKupS4", image: "https://img.youtube.com/vi/oT-lSZKupS4/maxresdefault.jpg" },
        { id: 18, name: "Client Success", quote: "Outstanding results for our family", youtubeId: "HzZnAw3whzQ", image: "https://img.youtube.com/vi/HzZnAw3whzQ/maxresdefault.jpg" },
        { id: 19, name: "Client Success", quote: "Commitment to finding the best deals", youtubeId: "koBtDC4KNRo", image: "https://img.youtube.com/vi/koBtDC4KNRo/maxresdefault.jpg" },
        { id: 20, name: "Client Success", quote: "Efficient and professional service", youtubeId: "WIMwRqTWJ-A", image: "https://img.youtube.com/vi/WIMwRqTWJ-A/maxresdefault.jpg" },
        { id: 21, name: "Client Success", quote: "Detailed analysis and market insights", youtubeId: "JWC7rlDDgfc", image: "https://img.youtube.com/vi/JWC7rlDDgfc/maxresdefault.jpg" },
        { id: 22, name: "Client Success", quote: "Negotiated the best terms for us", youtubeId: "6KtE9lNBprE", image: "https://img.youtube.com/vi/6KtE9lNBprE/maxresdefault.jpg" },
        { id: 23, name: "Client Success", quote: "Exceptional local market knowledge", youtubeId: "vLiopriS5HA", image: "https://img.youtube.com/vi/vLiopriS5HA/maxresdefault.jpg" },
        { id: 24, name: "Client Success", quote: "Great support for first-time buyers", youtubeId: "nW6iw5F4BWY", image: "https://img.youtube.com/vi/nW6iw5F4BWY/maxresdefault.jpg" },
        { id: 25, name: "Client Success", quote: "Strategic advice for property portfolio", youtubeId: "GzPuAhsJ-7o", image: "https://img.youtube.com/vi/GzPuAhsJ-7o/maxresdefault.jpg" },
        { id: 26, name: "Client Success", quote: "Found an off-market gem for us", youtubeId: "QhIK7kHBKfo", image: "https://img.youtube.com/vi/QhIK7kHBKfo/maxresdefault.jpg" },
        { id: 27, name: "Client Success", quote: "Thorough due diligence and assessment", youtubeId: "XJSod7XHcQo", image: "https://img.youtube.com/vi/XJSod7XHcQo/maxresdefault.jpg" },
        { id: 28, name: "Client Success", quote: "Simplifying the complex buying process", youtubeId: "ifqB5UC-S6Y", image: "https://img.youtube.com/vi/ifqB5UC-S6Y/maxresdefault.jpg" },
        { id: 29, name: "Client Success", quote: "Dedicated to our property goals", youtubeId: "ar5xbcnV4Do", image: "https://img.youtube.com/vi/ar5xbcnV4Do/maxresdefault.jpg" },
        { id: 30, name: "Client Success", quote: "Expertise that makes a difference", youtubeId: "ady1ChW69jc", image: "https://img.youtube.com/vi/ady1ChW69jc/maxresdefault.jpg" },
        { id: 31, name: "Client Success", quote: "Highly recommended property advocate", youtubeId: "MZCqnadokR8", image: "https://img.youtube.com/vi/MZCqnadokR8/maxresdefault.jpg" },
        { id: 32, name: "Client Success", quote: "Delivering real value to clients", youtubeId: "rJ9DhEke7P0", image: "https://img.youtube.com/vi/rJ9DhEke7P0/maxresdefault.jpg" },
    ],
    reviews: [
        { name: "John M.", rating: 5, date: "2 weeks ago", text: "Puja and Vishal are phenomenal! They found us an off-market property that perfectly matched our criteria. Their negotiation skills saved us thousands." },
        { name: "Priya S.", rating: 5, date: "1 month ago", text: "As first home buyers, we were overwhelmed. BuyersMatch guided us through every step and found a property we love within our budget." },
        { name: "Robert K.", rating: 5, date: "2 months ago", text: "Professional, knowledgeable, and genuinely care about their clients. Secured a fantastic investment property with great yield." },
        { name: "Michelle L.", rating: 5, date: "3 months ago", text: "The due diligence process was thorough. They identified issues we would have missed. Worth every penny!" },
    ],
    successStories: [
        { state: "SA", price: "$635,000", rent: "$550/week", yield: "4.5%", status: "Off Market" },
        { state: "WA", price: "$480,000", rent: "$480/week", yield: "5.2%", status: "Off Market" },
        { state: "QLD", price: "$720,000", rent: "$650/week", yield: "4.7%", status: "Off Market" },
    ],
    benefits: [
        "Expertise & Experience",
        "Client-Centric Approach",
        "Extensive Network Access",
        "Thorough Due Diligence",
        "Skilled Negotiation",
        "Trust & Transparency",
        "End-to-End Support",
        "Integrity & Honesty",
    ],
    processSteps: [
        { emoji: "📋", title: "Qualification", desc: "We understand your goals, budget, and requirements" },
        { emoji: "📈", title: "Strategy", desc: "Develop a tailored property investment strategy" },
        { emoji: "📍", title: "Suburb Selection", desc: "Identify high-growth suburbs matching your criteria" },
        { emoji: "🏠", title: "Property Selection", desc: "Shortlist and inspect suitable properties" },
        { emoji: "🔑", title: "Bring It Home", desc: "Negotiate, conduct due diligence, and settle" },
    ],
    services: [
        { icon: "🔍", title: "Property Search", desc: "Comprehensive search across on-market and off-market properties using our elite network." },
        { icon: "🏠", title: "Property Inspections", desc: "Thorough professional inspections and assessments of every potential match." },
        { icon: "📋", title: "Due Diligence", desc: "Complete property, legal, and financial due diligence to mitigate any risks." },
        { icon: "🤝", title: "Negotiation Support", desc: "Expert negotiation strategies to secure the best possible purchase terms." },
        { icon: "📊", title: "Transaction Support", desc: "End-to-end management of the entire settlement process and coordination." },
        { icon: "💡", title: "Expert Advice", desc: "Professional guidance and strategic market recommendations tailored to you." },
        { icon: "🎯", title: "Personalised Solutions", desc: "Tailored investment and lifestyle strategies for your unique requirements." },
        { icon: "🏗️", title: "Portfolio Strategy", desc: "Long-term planning for building wealth through strategic property acquisition." },
    ],
    blogs: [
        {
            id: "understanding-off-market-properties",
            title: "Understanding Off-Market Properties in Australia",
            image: "https://images.unsplash.com/photo-1582408921715-18e7806365c1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            date: "Feb 15, 2024",
            excerpt: "How to access exclusive deals that never hit the public listing sites."
        },
        {
            id: "first-home-buyer-guide-2024",
            title: "First Home Buyer Guide: 2024 Edition",
            image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            date: "Jan 28, 2024",
            excerpt: "Navigating grants, deposits, and market entry strategies for new buyers."
        },
        {
            id: "investment-property-yields-explained",
            title: "Investment Property Yields Explained",
            image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            date: "Jan 12, 2024",
            excerpt: "Why gross yield isn't the only metric you should care about as an investor."
        },
        {
            id: "the-psychology-of-negotiation",
            title: "The Psychology of Negotiation in Real Estate",
            image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            date: "Dec 05, 2023",
            excerpt: "Mastering the art of closing the deal without overpaying for your dream home."
        }
    ],
    whoWeHelp: [
        {
            title: "Property Investors",
            image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            content: "Building property portfolios across Australia. We identify high-growth opportunities and optimize your investment strategy for maximum yield."
        },
        {
            title: "SMSF Investors",
            image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            content: "Specialized property acquisition for Super Funds. We ensure full compliance while maximizing long-term returns for your retirement portfolio."
        },
    ]
};
